const mongoose = require("mongoose");

const leadSchema = new mongoose.Schema({
  Id: { type: String, default: "" },
  alternate_no: { type: String, default: "" },
  associate_status: { type: Boolean, default: false },
  budget: { type: String, default: "" },
  contact_no: { type: String, default: "" },
  contact_owner_email: { type: String, default: "" },
  country_code: { type: String, default: "" },
  lead_type: { type: String, default: "Data" },
  created_at: { type: Date, default: Date.now },
  created_by: { type: String, default: "" },
  customer_image: { type: String, default: "" },
  customer_name: { type: String, default: "" },
  
  // old before migration
  // email: { type: String, default: new Date() },

  // new after migration
  email: { type: String, default: "" },
  feedback_time: { type: Date, default: "" },
  lead_assign_time: { type: Date, default: Date.now },
  lead_source: { type: String, default: "" },
  location: { type: String, default: "" },
  lost_reason: { type: String, default: "" },
  modified_at: { type: Date, default: Date.now  },
  call_response_time: { type: Date, default:""},
  next_follow_up_date_time: { type: Date, default: "" },
  next_follow_up_type: { type: String, default: "" },
  not_int_reason: { type: String, default: "" },
  organization_id: { type: String, default: "" },
  other_lost_reason: { type: String, default: "" },
  other_not_int_reason: { type: String, default: "" },
  previous_owner: { type: String, default: "" },
  project: { type: String, default: "" },
  property_stage: { type: String, default: "" },
  property_type: { type: String, default: "" },
  source_status: { type: Boolean, default: false },
  stage: { type: String, default: "" },
  stage_change_at: { type: Date, default: Date.now  },
  transfer_status: { type: Boolean, default: false },
  uid: { type: String, default: "" },
  addset: { type: String, default: "" },
  campaign: { type: String, default: "" },
  inventory_type: { type: String, default: "" },
  property_sub_type: { type: String, default: "" },
  transfer_reason: { type: String, default: "" },
  previous_owner_1: { type: String, default: "" },
  previous_owner_2: { type: String, default: "" },
  transfer_by_1: { type: String, default: "" },
  transfer_by_2: { type: String, default: "" },
  previous_stage_1: { type: String, default: "" },
  previous_stage_2: { type: String, default: "" },
  call_back_reason: { type: String, default: "" },
  is_button_called: { type: Boolean, default: false },
  gender: { type: String, default: "" },
  marital_status: { type: String, default: "" },
  address: { type: String, default: "" },
  dob: { type: Date, default: null },
  anniversary_date: { type: Date, default: null },
  business_vertical: { type: String, default: "" },
  api_forms: { type: String, default: "" },
  state: { type: String, default: "" },
  reenquired: { type: Boolean, default: false },
 
  // lead auto rotation or shuffling 
  leadDistributionId:{type:String, default:""},
  autoRotationEnabled:{
    type:String,
    enum:["ON","OFF","HOLD"],
    default:"OFF"
},
  // autoRotationTime:{type:Number},
  autoRotationOwners:{type:[String],default:[]},
  nextRotationAt:{type:Date},
  requirement_Type:{type: String, default: 'NEW PROJECT' },
  unit_no:{type:String, default:""},
  property_id:{type:String, default:""},
  city:{type:String, default:""},
  country:{type:String, default:""},
  contact_message_details:{type:String, default:""},
  mb_contact_id:{type:String, default:""},
});

const newLead = mongoose.model("contacts", leadSchema);

module.exports = newLead;
